---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/blockinfile_module.html#examples
- name: add entry to hosts
  hosts: servers
  become: yes
 
  tasks:
  - name: add host entries
    ansible.builtin.blockinfile:
      path: /etc/hosts
      block: |
        {{ item.ip }} {{ item.name }}
      marker: "# (mark) ANSIBLE MANAGED BLOCK {{ item.name }}"
    loop:
    - { name: esxi, ip: 192.168.1.11 }