# voeg user "test" toe
# https://https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html#examples.ansible.com/ansible/latest/collections/ansible/builtin/blockinfile_module.html#examples
- name: add user to host
  hosts: servers
  become: yes
  tasks:
    - name: add user
      ansible.builtin.user:
        name: test
        create_home: yes
